showline/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
]

timelineweb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('showline/', include('showline.urls')),
    path('user/', include('user.urls',namespace="user")),
]

user/urls.py
from django.urls import path

from user import views

app_name="user"

urlpatterns = [
    path('login/', views.login,name='login'),
    path('register/', views.register,name='register'),
    path('logout/', views.logout),
]

showline/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(models.Model):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

showline/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.shortcuts import render

# Create your views here.

def login(request):
    return render(request,'user/login.html')

def register(request):
    return render(request,'user/register.html')

def logout(request):
    return render(request,'')

templates/showline/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>

</body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href='{% static "css/login.css" %}'>

    <meta charset="UTF-8">
    <title>登录</title>
  <style ></style>

</head>
<body>

<!--login-->
<div class="textCenter">
     <div class="form-box">
         <form class="form">
           <span class="title">Login</span>
           <span class="subtitle">write your name and password</span>
           <div class="form-container">
               <input type="text" class="input" placeholder=" Name">
			   <input type="password" class="input" placeholder="Password">
           </div>
           <button>Login</button>

         </form>
     <div class="form-section">
     <p>Need an account? <a href="{% url 'user:register' %}">Sign up </a> </p>
     </div>
</div>

</div>




</body>
</html>

templates/user/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href='{% static "css/login.css" %}'>

    <meta charset="UTF-8">
    <title>登录</title>
  <style ></style>

</head>
<body>

<!--login-->
<div class="textCenter">
     <div class="form-box">
         <form class="form">
           <span class="title">Sign up</span>
           <span class="subtitle">Create a free account with your email.</span>
           <div class="form-container">
               <input type="text" class="input" placeholder="Full Name">
			   <input type="email" class="input" placeholder="Email">
			   <input type="password" class="input" placeholder="Password">
           </div>
           <button>Sign up</button>
         </form>

     <div class="form-section">
     <p>Have an account? <a href="{% url 'user:login' %}">Log in</a> </p>
     </div>
</div>

</div>




</body>
</html>